Update list.py
Example provided in docs leads to  below error. I tried with the proposed workaround it works fine now.
Traceback (most recent call last):
   File "PanelList.py", line 37, in <module>
     MainApp().run()
   File "C:\Users\ishan\Desktop\pyProjects\kivy_venv\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "C:\Users\ishan\Desktop\pyProjects\kivy_venv\lib\site-packages\kivy\app.py", line 919, in _run_prepare
     root = self.build()
   File "PanelList.py", line 34, in build
     return Builder.load_string(KV)
   File "C:\Users\ishan\Desktop\pyProjects\kivy_venv\lib\site-packages\kivy\lang\builder.py", line 408, in load_string
     self._apply_rule(
   File "C:\Users\ishan\Desktop\pyProjects\kivy_venv\lib\site-packages\kivy\lang\builder.py", line 659, in _apply_rule
     child = cls(__no_builder=True)
 TypeError: __init__() missing 2 required positional arguments: 'source' and 'mipmap'