Fix AttributeError on segmented button created in declarative python
In segmentedbutton.kv, we need to check if the MDSegmentButtonIcon
object actually has a parent.parent before checking container's parent
_label, otherwise you may get the following error: AttributeError:
'NoneType' object has no attribute 'parent'

Fix #1735

Signed-off-by: Alberto Pianon <alberto@pianon.eu>